import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Leaf, Scan, Activity, ArrowRight, Zap } from 'lucide-react';
import { Navbar } from '../components/layout/Navbar';
import { PageWrapper } from '../components/layout/PageWrapper';
import { Button } from '../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { BlobBackground } from '../components/layout/BlobBackground';

export default function HomeNew() {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-black text-white selection:bg-emerald-500/30">
            <div className="fixed inset-0 z-0">
                <BlobBackground />
                <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 brightness-100 contrast-150"></div>
            </div>

            <Navbar />

            <PageWrapper className="relative z-10 flex min-h-screen flex-col items-center justify-center px-4 pt-20">
                <div className="mx-auto max-w-4xl text-center">
                    <div className="mb-6 inline-flex items-center rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-sm font-medium text-emerald-400 backdrop-blur-md">
                        <span className="flex h-2 w-2 rounded-full bg-emerald-400 mr-2 animate-pulse"></span>
                        AI-Powered Plant Diagnostics
                    </div>

                    <h1 className="mb-6 bg-gradient-to-br from-white via-gray-100 to-gray-500 bg-clip-text text-5xl font-bold tracking-tight text-transparent sm:text-7xl">
                        Heal your garden with <br />
                        <span className="text-emerald-500">Botanic Intelligence</span>
                    </h1>

                    <p className="mb-10 text-lg text-gray-400 sm:text-xl max-w-2xl mx-auto">
                        Upload a photo of your sick plant and let our advanced AI diagnosis engine identify diseases and recommend treatments in seconds.
                    </p>

                    <div className="flex flex-col items-center justify-center space-y-4 sm:flex-row sm:space-x-4 sm:space-y-0">
                        <Button size="lg" className="group" onClick={() => navigate('/analysis')}>
                            Start Diagnosis
                            <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
                        </Button>
                        <Button variant="secondary" size="lg" onClick={() => window.open('https://github.com/Soumo9831/Plant-Disease', '_blank')}>
                            View on GitHub
                        </Button>
                    </div>
                </div>

                <div className="mt-20 grid w-full max-w-5xl gap-6 sm:grid-cols-3 px-4">
                    <FeatureCard
                        icon={<Zap className="h-6 w-6 text-yellow-400" />}
                        title="Instant Results"
                        description="Get accurate disease predictions in milliseconds using our optimized deep learning model."
                    />
                    <FeatureCard
                        icon={<Scan className="h-6 w-6 text-blue-400" />}
                        title="99% Accuracy"
                        description="Trained on thousands of plant images to ensure reliable detection of common pathogens."
                    />
                    <FeatureCard
                        icon={<Activity className="h-6 w-6 text-emerald-400" />}
                        title="Expert Advice"
                        description="Receive actionable treatment plans and care tips generated by our integrated LLM agent."
                    />
                </div>
            </PageWrapper>
        </div>
    );
}

function FeatureCard({ icon, title, description }) {
    return (
        <Card variant="holo" className="bg-white/5 hover:bg-white/10 transition-colors">
            <CardHeader>
                <div className="mb-2 inline-flex h-10 w-10 items-center justify-center rounded-lg bg-white/10">
                    {icon}
                </div>
                <CardTitle className="text-lg">{title}</CardTitle>
            </CardHeader>
            <CardContent>
                <p className="text-gray-400">{description}</p>
            </CardContent>
        </Card>
    );
}
